########################################################################################################
#
#
#                                      Matrix Anti-Cheat
#                                          config.yml
#
########################################################################################################

# Player Latency Protection
# Decreases the amount of violations increasing for players with high latency
player_latency_protection:
  # Enable this feature?
  enable: true


# Server Lag Protection
# Automatically disables some checks when your server is lagging
tps_protection:
  # Enable this feature?
  enable: true

  # Min TPS
  min_tps: 17.0


# Log violations to file
# If you are using BungeeCord, I recommend not enabling this feature as it will create many useless log files
log_file: true

# Disable bypass permission
# if you don't want to operator bypass Matrix or you need to test Matrix in OP mode,you can enable this
disable_bypass_permission: false
