#### MATRIX CONFIG FILE
#                         MATRIX ANTI CHEAT
#             文件: config.yml  | 这里是全局自定义的配置
#
# 链接s:
#   1. 问题收集器: https://github.com/jiangdashao/Matrix-Issues/issues
#   2. SpigotMC 主页: https://www.spigotmc.org/resources/64635/
#   3. bStats: https://bstats.org/plugin/bukkit/Matrix
#   4. Discord 服务器: https://discord.gg/pEvY55J
#
# 贡献者:
#   Performance#1955: 提交了若干的BUG并管理问题提交区。
#   Zak#6435 & Alex#2237: 提供测试服务器并提交了若干的BUG.
#   Kruize#9138 & VariationTime#2942: 提交了若干的BUG.
#
# 感谢使用 Matrix <3

## 需要在启动服务器后进行版本检查吗？
check_update: true

## 玩家滞后补偿
# 介绍: 针对玩家的延迟，会适当的提高
# VL，减慢执行处罚指令的时间（checks.yml）
# 对内存小的服务器比较友好。
player_latency_protection:
  # 启用这一特性？
  enable: true
  
## 踢出雷击效果
# 如果有个人被使用指令 /matrix kick 踢出，应该
# 生成雷击效果吗
kick_strike_lightning: true

## 隐藏模式
# 如果你启动了隐藏模式, Matrix 将不会对玩家进行拉回
# 亦或是取消非法动作. 我不建议将本项启用,
# 它将会使作弊者有机可乘.
ghost_mode: false

## 云服务
# Matrix 可以连接到云服务器，并提供
# 一些云服务，你也可以购买付费方案来获取更多的检测以及服务！
cloud:
  # 启用云服务？
  enable: true
  
  # 登陆用户名
  user: ''

  # 登陆密码
  password: ''

  # 当您被验证为付费用户后关闭云服务
  # 如果你不需要云服务但是你需要付费服务
  # 你可以将此项设置为 true
  auto_close_after_verified: false
  
## 服务器滞后补偿
# 介绍: 当你服务器卡顿时，将会自动关闭一些功能
# 这个可以防止发生大部分的误报，
# 但并不是一定。
tps_protection:
  # 启用这一特性？
  enable: true

  # 激发本项保护的最低TPS
  min_tps: 17.0

## 记录VL
# 介绍: 将全部的VL记录到一个文件中，你可以在
# /plugins/Matrix/logs 找到。
# 注意: 如果您在使用 Bungeecord, 我推荐设置这个成
# FALSE. 这个将会提供无用的信息并储存到您的硬盘中
# 占用硬盘空间。
log_file: true

## 禁用绕过权限
# 介绍: 设置这项选项到 FALSE 后, 将会强制 Matrix
# 对服务器中的每一名玩家进行检测, 包括
# 拥有OP权限的玩家. 设置这个为TRUE后
# 你可以在不撤销他们OP权限的情况下，
# 进行一些不必要的测试。
disable_bypass_permission: false

## 重新登录时间
# 玩家在被 Matrix处罚后，需要等待多长时间才能重新登录到服务器？ (秒)
# 当然, 你也可以将其设置为 -1 来关闭此项特性。
relog_time: 5

## 禁用检测
# 你可以在这里禁用一个特别的子检测, 用以替代关闭
# 一整个检测, 你可以在 Verbose信息 的最后面找到
# 检测项的名称
# 例子: 如果你在下面添加了 "speed.web", 快速过蜘蛛网检测
# 将会被禁用。
disabled_components:
  - 'example entry'
